### PR TITLE
added docId so that the PUT operation works with CouchDB

### PR DESCRIPTION
**Pull request by manojsaxenatda**
### Description
added docId so that the PUT operation is invoked with CouchDB.  This is used to modify an existing document using couchDB PUT method.

#### Related issues
- connect to #64

### Checklist

- [ ] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by dhmlau** [comment]
@manojsaxenatda, thanks for the PR.  
Could you please sign the CLA https://cla.strongloop.com/agreements/strongloop/loopback-connector-couchdb2? 

Also, could you please fix the commit linter error? 
```
**  Linting commit logs
**
**  1 problems found:
**    bdc7482 - added docId so that the PUT operation works with Co: First line should be 50 characters or less (saw 56)
**
```
Please refer to our commit message guideline for details: https://loopback.io/doc/en/contrib/git-commit-messages.html. Thanks.

**Comment by jannyHou** [comment]
@slnode test please

**Comment by manojsaxenatda** [comment]
Hi Janny, 
I got an automated email about no activity.  Let me know if I can be of help.
Thank you

**Comment by dhmlau** [comment]
Didn't see the logs, probably it's been too long.  kicking it off again.
@slnode test please

**Pull request closed without merging**
